### ISSUE TITLE
Send informations in channel

### ISSUE THREAD

**Issue by Noqh-Dev** [iFraan/rocketleague.js#2]
Hello I wan't to know if we can send informations in a message on discord ? Maybe that:
![image](https://user-images.githubusercontent.com/70452399/235276883-59ef2f19-5fac-47d0-aaad-c768a1413a78.png)
However I only get User:
![image](https://user-images.githubusercontent.com/70452399/235276954-1b36ee39-69ef-4a61-8f89-05de6d4456e1.png)
Thanks for your help.

**Comment by iFraan** [comment]
Yep, you can send the info in discord. However, that method returns an object.

So, your options are either parsing it like
```js
await interaction.reply(JSON.stringify(user.getUserInfo(), null, '\t'));
```

or accesing the property direcly like
```js
const info = user.getUserInfo();
await interaction.reply(`Username ${info.name}`);
```
or
```js
const { name, avatar } = user.getUserInfo();
await interaction.reply(`Username ${name}`);
```

.
.


_note from ignorance_: 
I'm not so sure that discordjs .reply method 'prints' anything more than the first parameter. The logic would indicate that the second parameter is for passing options only.
Thats why in my examples I'm using **Template literals**. 
I can be wrong tho.

**Anyhow**, let me know.

**Comment by Noqh-Dev** [comment]
Do you think it is possible to indicate the "PLATFORM.<platform>" with a choice of a slash command like for example this since I have an error which tells me that "the specified platform is invalid":
![image](https://user-images.githubusercontent.com/70452399/235298750-4f08cf0e-3b99-4fc4-996c-99d9e4d4545e.png)
![Screenshot_2](https://user-images.githubusercontent.com/70452399/235298795-2edd0ca5-b5e9-4fa4-924c-13c445788225.png)

Yes the second and the third solution work however the first does not work

**Comment by iFraan** [comment]
I recommend you read [Working with Objects/accessing properties](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_objects#accessing_properties) before applying the 'fix' I'm providing since it will give you a better understanding of what is going on.

First let's refresh what the PLATFORM variable looks like:
```js
const PLATFORM = {
    Steam: 'steam',
    Epic: 'epic',
    Playstation: 'psn',
    Xbox: 'xbl'
}
```
So you can use its keys/values with 
```js
Object.keys(PLATFORM) // 'Steam', 'Epic', 'Playstation', 'Xbox'
// or
Object.values(PLATFORM) // 'steam', 'epic', 'psn', 'xbl'
```

When you are using `PLATFORM.platform` you are trying to access the `platform` property of `PLATFORM`; which is **undefined**, hence the 'invalid platform' error.

You can pass the platform as a plain string as
```js
const platform = 'psn';
RLAPI.fetchUser(platform, playerName);
```

or access properties in a bracket notation. (Which i recommend)
```js
const platform = 'Steam';  // Please note that case IS important here
await RLAPI.fetchUser(PLATFORM[platform], playerName);
```

Also you can have a simple helper to do it for you and pass it directly
```js
const choosePlatform = (query) => {
    const text = query.toLowerCase();
    let platform = PLATFORM.Steam;
    if (text.includes('epic')) 
        platform = PLATFORM.Epic;
    if (text.includes('playstation') || text.includes('psn')) 
        platform = PLATFORM.Playstation;
    if (text.includes('xbox') || text.includes('xbl')) 
        platform = PLATFORM.Xbox;

    return platform;
}

const platform = choosePlatform('ePic');
await RLAPI.fetchUser(platform, playerName);
```

There are multiple approaches that you can take, and not limited to the these examples. Either way, closing this since neither of these issues are related to the library.
Further questions, _within reason_, you can send it to my discord at iFraan_#4175.
